server:
  port: 8080
  servlet:
    context-path: /pd1

spring:
  application:
    name: account-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  data:
    mongodb:
      host: sam-cosmos-1.mongo.cosmos.azure.com
      port: 10255
      username: ${azure-cosmosdb-username}
      password: ${az-cosmosdb-password}
      database: cosmos-pd1
      ssl:
        enabled: true