server:
  port: 8080

spring:
  cloud:
    azure:
      keyvault:
        secret:
          endpoint: https://az-cosmos-db1-keyvault.vault.azure.net/

      cosmos:
        endpoint: ${az-cosmosdb-uri}
        key: ${az-cosmosdb-password}
        database: cosmos-pd1