server:
  port: 8080
  servlet:
    context-path: /pd1

spring:
  application:
    name: account-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  data:
    mongodb:
       uri: mongodb://${azure-cosmosdb-username}:${az-cosmosdb-password}@${az-cosmosdb-uri}:10255/cosmos-pd1?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

rate-limit:
  requests: 10
  duration-minutes: 1